#!/usr/bin/env python
import os
import re

def check_filetype(f):
    filetypes = ['mkv', 'mp4', 'avi']
    return True in [f.endswith(filetype) for filetype in filetypes]

def playlist():
    return _sort([f for f in os.listdir('.') if check_filetype(f)])

def load_config():
    return position and file

def _key(s):
    return [int(c) if c.isdigit() else c for c in re.split('([0-9]+)', s)][1:]

def _sort(l):
    convert = lambda text: int(text) if text.isdigit() else text 
    alphanum = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted(l, key=_key)

def play(filename):
    d = os.getcwd()
    path = os.path.join(d, filename)
    return os.system('mplayer "{}" -heartbeat-cmd "wch_log {}"').format(path)

if __name__ == '__main__':
    import sys
    # get playlist
    # check for saved position
    # load the last position
    # or play the first episode
    args = sys.argv
    if len(args) > 1:
        print 'cding to', args[1]
        os.chdir(args[1])
    for a in playlist():
        print a
        if play(a) == 2:
            break
